# Указываем путь к Java 17
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-17.0.16.0.8-alt1.x86_64

# Дополнительные настройки для Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true

# Отключаем проверку лицензий (временно)
android.builder.sdkCheck=false

# Включаем Hermes
hermesEnabled=true
